package com.schoolpartime.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.schoolpartime.dao.entity.ChatRecords;
import com.schoolpartime.dao.entity.UserInfo;

import com.schoolpartime.dao.ChatRecordsDao;
import com.schoolpartime.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRecordsDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final ChatRecordsDao chatRecordsDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRecordsDaoConfig = daoConfigMap.get(ChatRecordsDao.class).clone();
        chatRecordsDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        chatRecordsDao = new ChatRecordsDao(chatRecordsDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(ChatRecords.class, chatRecordsDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        chatRecordsDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public ChatRecordsDao getChatRecordsDao() {
        return chatRecordsDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
