package com.schoolpartime.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.schoolpartime.dao.entity.UserInfo;
import com.schoolpartime.dao.entity.SearchTitle;

import com.schoolpartime.dao.UserInfoDao;
import com.schoolpartime.dao.SearchTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig searchTitleDaoConfig;

    private final UserInfoDao userInfoDao;
    private final SearchTitleDao searchTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        searchTitleDaoConfig = daoConfigMap.get(SearchTitleDao.class).clone();
        searchTitleDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        searchTitleDao = new SearchTitleDao(searchTitleDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(SearchTitle.class, searchTitleDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        searchTitleDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public SearchTitleDao getSearchTitleDao() {
        return searchTitleDao;
    }

}
